music_library_django/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import Index, DeleteTrack, AddTrack, EditTrack, SearchTrack

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view()),
    path('delete_track/<int:pk>', DeleteTrack.as_view()),
    path('add_track/', AddTrack.as_view()),
    path('edit_track/<int:pk>/', EditTrack.as_view()),
    path('search_track/', SearchTrack.as_view()),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

core/models.py
from django.db import models


class Track(models.Model):
    performer = models.CharField(max_length=255)
    track = models.CharField(max_length=255)
    duration = models.CharField(max_length=5)

core/views.py
from re import match

from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import DeleteView, CreateView, UpdateView
from django.views.generic.base import TemplateView


from core.models import Track


def check_duration(duration):
    if not match(r'^[1-9]\d*\:[0-5][0-9]$', duration):
        return "enter duration like 00:00"
    else:
        return ''


class Index(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        tracks = Track.objects.all()
        return {
            'tracks': tracks
        }


class DeleteTrack(DeleteView):
    model = Track
    success_url = '/'


class AddTrack(CreateView):
    template_name = 'add_track.html'
    model = Track
    fields = ('performer', 'track', 'duration')

    def get_context_data(self, **kwargs):
        return {
            'duration_error': '',
            'performer': '',
            'track': '',
            'duration': ''
        }

    def form_valid(self, form):
        duration = form.cleaned_data['duration']
        duration_error = check_duration(duration)
        performer = form.cleaned_data['performer']
        track = form.cleaned_data['track']
        if duration_error:
            return render(self.request, self.template_name, {
                'duration_error': duration_error,
                'performer': performer,
                'track': track,
                'duration': ''
            })
        else:
            track = form.save(commit=True)
            track.save()
            return redirect('/')


class EditTrack(UpdateView):
    model = Track
    fields = ('performer', 'track', 'duration')
    template_name = 'edit_track.html'

    def form_valid(self, form):
        track_id = self.kwargs.get('pk', '')
        duration_error = check_duration(form.cleaned_data['duration'])
        track = Track.objects.filter(id=track_id).get()
        if duration_error:
            return render(self.request, self.template_name, {
                'duration_error': duration_error,
                'track': track,
            })
        else:
            track_save = form.save(commit=True)
            track_save.save()
            return redirect('/')


class SearchTrack(TemplateView):
    model = Track
    template_name = 'search_track.html'

    def get_context_data(self, **kwargs):
        search_query = self.request.GET.get('search', '')
        if search_query != '':
            search_query_lst = search_query.split(' ')
            likes = []
            for word in search_query_lst:
                likes.append(Q(track__contains=word))
                likes.append(Q(performer__contains=word))

            tracks = Track.objects.filter(
                *likes,
                _connector='OR'
            )

        else:
            tracks = []

        return {
            'tracks': tracks
        }

core/templates/add_track.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <form action="/add_track/" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_performer">Performer</label>
            <input type="text" value="{{performer}}" required class="form-control" id="id_performer" name="performer">
        </div>
        <div class="form-group">
            <label for="track">Track</label>
            <input type="text" value="{{track}}" required class="form-control" id="track" name="track">
        </div>
        <div class="form-group">
            <label for="duration">Duration</label>
            <input type="text" value="{{duration}}" required class="form-control" id="duration" name="duration">
            <h6>{{duration_error}}</h6>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/django_registration/registration_complete.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h2>You are successfully registered</h2>
    </div>
{% endblock %}

core/templates/django_registration/registration_form.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <form method="post">
        <form action="/url/to/submit/" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">Login</button>
            {% endbuttons %}
        </form>
    </form>
</div>
{% endblock %}

core/templates/edit_track.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_performer">Performer</label>
            <input value="{{track.performer}}" type="text" class="form-control" id="id_performer" name="performer">
        </div>
        <div class="form-group">
            <label for="track">Track</label>
            <input value="{{track.track}}" type="text" class="form-control" id="track" name="track">
            <label for="duration">Duration</label>
            <input value="{{track.duration}}" type="text" class="form-control" id="duration" name="duration">
            <h6>{{duration_error}}</h6>
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>
{% endblock %}

core/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Performer</th>
                <th scope="col">Track</th>
                <th scope="col">Duration</th>
                <th scope="col">DELETE</th>
                <th scope="col">EDIT</th>
            </tr>
            </thead>
            <tbody>
            {% for track in tracks %}
                <tr>
                    <td>{{ track.id }}</td>
                    <td>{{ track.performer }}</td>
                    <td>{{ track.track }}</td>
                    <td>{{ track.duration }}</td>
                    <td>
                        <form method="post" action="/delete_track/{{ track.id }}" class="d-inline-block">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-link">Delete</button>
                        </form>

                    </td>
                    <td>
                        <a href="/edit_track/{{ track.id }}/">Edit</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

core/templates/layout.html
<!doctype html>
<html>
<head>
    <title>Music Library</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="/accounts/logout">Logout</a>
            {% else %}
                <a class="navbar-brand" href="/accounts/login">Login</a>
                <a class="navbar-brand" href="/accounts/register/">Registration</a>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/add_track/">Add track</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="/search_track/">Search track</a>
            </li>
        </ul>
        <span class="navbar-text">
              Music library
            </span>
    </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

core/templates/search_track.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <form method="get" action="/search_track/">
            <div class="form-group">
                <label for="search">to search enter performer, track or duration </label>
                <input type="text" class="form-control" id="search" name="search">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="container">
        {% if tracks|length > 0 %}
            <table class="table mt-3">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Performer</th>
                    <th scope="col">Track</th>
                    <th scope="col">Duration</th>
                    <th scope="col">DELETE</th>
                    <th scope="col">EDIT</th>
                </tr>
                </thead>
                <tbody>
                {% for track in tracks %}
                    <tr>
                        <td>{{ track.id }}</td>
                        <td>{{ track.performer }}</td>
                        <td>{{ track.track }}</td>
                        <td>{{ track.duration }}</td>
                        <td>
                            <form method="post" action="/delete_track/" class="d-inline-block">
                                <input type="hidden" name="id_performer" value="{{ track.id }}">
                                <button type="submit" class="btn btn-link">Delete</button>
                            </form>
                        </td>
                        <td>
                            <a href="/edit_track/{{ track.id }}/">Edit</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h3>Tracks not found</h3>
        {% endif %}
    </div>
{% endblock %}